//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarFeature
    {
        public CarFeature()
        {
            this.IndividualCars = new HashSet<IndividualCar>();
        }
    
        public int FeatureID { get; set; }
        public string Car_Feature_Description { get; set; }
    
        public virtual ICollection<IndividualCar> IndividualCars { get; set; }
    }
}
