//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public CarModel()
        {
            this.IndividualCars = new HashSet<IndividualCar>();
        }
    
        public int ModelID { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public int NumberOfSeats { get; set; }
        public double EngineSize { get; set; }
    
        public virtual ICollection<IndividualCar> IndividualCars { get; set; }
    }
}
