//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Sold
    {
        public int Car_Sold_ID { get; set; }
        public int Car_For_Sale_Id { get; set; }
        public int Customer_Id { get; set; }
        public decimal Sale_Price { get; set; }
        public System.DateTime Date_Sold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual IndividualCar IndividualCar { get; set; }
    }
}
